<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>LUI</string>
    <key>scopeName</key>
    <string>source.lui</string>
    <key>patterns</key>
<array>
    <dict>
        <key>name</key>
        <string>punctuation.definition.bracket</string>
        <key>match</key>
        <string>[\[\]{}()]</string>
    </dict>
    <dict>
        <key>name</key>
        <string>constant.numeric</string>
        <key>match</key>
        <string>\b\d+\.?\d*\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>comment.line</string>
        <key>begin</key>
        <string>//</string>
        <key>end</key>
        <string>$</string>
    </dict>
    <dict>
        <key>name</key>
        <string>comment.line</string>
        <key>begin</key>
        <string>--</string>
        <key>end</key>
        <string>$</string>
    </dict>
    <dict>
        <key>name</key>
        <string>string.quoted.single</string>
        <key>begin</key>
        <string>'</string>
        <key>end</key>
        <string>'</string>
    </dict>
    <dict>
        <key>name</key>
        <string>string.quoted.double</string>
        <key>begin</key>
        <string>&quot;</string>
        <key>end</key>
        <string>&quot;</string>
    </dict>
    <dict>
        <key>name</key>
        <string>constant.language.lua</string>
        <key>match</key>
        <string>\.{3}</string>
    </dict>
    <dict>
        <key>name</key>
        <string>variable.parameter.function</string>
        <key>match</key>
        <string>(?&lt;=\()[^'&quot;\)]*(?=\))</string>
    </dict>
    <dict>
        <key>name</key>
        <string>variable.parameter.function.lua</string>
        <key>match</key>
        <string>(?&lt;=function\()([^\)]+)</string>
    </dict>
    <dict>
        <key>name</key>
        <string>string.quoted.single</string>
        <key>match</key>
        <string>'[^']*'</string>
    </dict>
    <dict>
        <key>name</key>
        <string>string.quoted.double</string>
        <key>match</key>
        <string>&quot;[^&quot;]*&quot;</string>
    </dict>
    <dict>
        <key>name</key>
        <string>support.variable.id</string>
        <key>match</key>
        <string>(?&lt;=id:\s*)\b[A-Za-z][A-Za-z0-9_]*\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>entity.name.tag.equations</string>
        <key>match</key>
        <string>\b(linear|quadratic|cubic|quartic|quintic|sinusoidal|exponential|circular|bounce|back|elastic|ease-in|ease-out|ease-inout)\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>entity.name.tag.anchors</string>
        <key>match</key>
        <string>(?&lt;=anchors\.[A-Za-z][A-Za-z0-9_]*:\s*)\b[A-Za-z][A-Za-z0-9_.]*\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>entity.name.tag.align</string>
        <key>match</key>
        <string>(?&lt;=align:\s*)\b[A-Za-z][A-Za-z0-9_]*\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>entity.name.tag.layout</string>
        <key>match</key>
        <string>(?&lt;=layout:\s*)\b[A-Za-z][A-Za-z0-9_]*\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>constant.language.boolean</string>
        <key>match</key>
        <string>\b(true|false)\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>constant.numeric</string>
        <key>match</key>
        <string>\b\d+(?=(dp|rp|rh|rw|p|ph|pw|sp|px|mm|in|pt|%|em|ms)\b)</string>
    </dict>
    <dict>
        <key>name</key>
        <string>keyword.control.unit</string>
        <key>match</key>
        <string>(?&lt;=\d)(dp|rp|rh|rw|p|ph|pw|sp|px|mm|in|pt|%|em|ms)\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>keyword.control.unit</string>
        <key>match</key>
        <string>(?&lt;=: )\b(dp|rp|rh|rw|p|ph|pw|sp|px|mm|in|pt|%|em|ms)\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>keyword.control.state</string>
        <key>match</key>
        <string>\$!?\b[A-Za-z][A-Za-z0-9_]*\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>keyword.operator</string>
        <key>match</key>
        <string>(\.{2}|!|\$|\%|\*)</string>
    </dict>
    <dict>
        <key>name</key>
        <string>keyword.operator</string>
        <key>match</key>
        <string>(\s+-\s+)|(^-\s+)|(\s+-$)|(^-$)|(-(?=\d))</string>
    </dict>
    <dict>
        <key>name</key>
        <string>keyword.control.lua</string>
        <key>match</key>
        <string>\b(if|else|elseif|then|end|and|for|do|while|repeat|until|break|return|local|function)\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>keyword.operator.comparison</string>
        <key>match</key>
        <string>(?&lt;=\b(if|elseif|while|until)\b.*)(&gt;|&lt;|&gt;=|&lt;=|==|~=)</string>
    </dict>
    <dict>
        <key>name</key>
        <string>constant.numeric.float</string>
        <key>match</key>
        <string>\b\d+\.\d+\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>constant.numeric.integer</string>
        <key>match</key>
        <string>\b\d+\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>constant.numeric.fraction</string>
        <key>match</key>
        <string>\b\d+/\d+\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>constant.numeric</string>
        <key>match</key>
        <string>\b\d+(\.\d+)?s\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>string.unquoted.path</string>
        <key>match</key>
        <string>(?&lt;=:\s*)[A-Za-z0-9_/]*\/[A-Za-z0-9_/]*</string>
    </dict>
    <dict>
        <key>name</key>
        <string>variable.other.table</string>
        <key>match</key>
        <string>\b[A-Za-z_][A-Za-z0-9_]*\b(?=\.)</string>
    </dict>
    <dict>
        <key>name</key>
        <string>support.function</string>
        <key>match</key>
        <string>(?&lt;=\.)\b[A-Za-z_][A-Za-z0-9_]*\b(?=\()</string>
    </dict>
    <dict>
        <key>name</key>
        <string>support.function</string>
        <key>match</key>
        <string>\b[A-Za-z_][A-Za-z0-9_]*\b(?=\()</string>
    </dict>
    <dict>
        <key>name</key>
        <string>storage.type.command</string>
        <key>match</key>
        <string>@[\w-]+</string>
    </dict>
    <dict>
        <key>name</key>
        <string>support.class</string>
        <key>match</key>
        <string>^\b[A-Za-z][A-Za-z0-9_]*\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>support.class</string>
        <key>match</key>
        <string>(?&lt;=&lt;\s)\b[A-Za-z][A-Za-z0-9_]*\b</string>
    </dict>
    <dict>
        <key>name</key>
        <string>entity.name.class</string>
        <key>match</key>
        <string>^\s*[A-Z][A-Za-z0-9_.]*\s*$</string>
    </dict>
    <dict>
        <key>name</key>
        <string>entity.name.tag.others</string>
        <key>match</key>
        <string>(?&lt;=:\s*)\b[A-Za-z][A-Za-z0-9_.-]*\b</string>
    </dict>
</array>

</dict>
</plist>